// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Extractor is an autogenerated mock type for the Extractor type
type Extractor struct {
	mock.Mock
}

// GetUserID provides a mock function with given fields: ctx
func (_m *Extractor) GetUserID(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWebSocketCredentials provides a mock function with given fields: r
func (_m *Extractor) GetWebSocketCredentials(r *http.Request) (string, string) {
	ret := _m.Called(r)

	var r0 string
	if rf, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(*http.Request) string); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}
