version: '3.4'
services:

# Gateway
  wetalk-gateway:
    build:
      context: ./backend/gateway
      dockerfile: ./Dockerfile
    image: wetalk-gateway
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - wetalk-network

# DB
  wetalk-db:
    image: mysql:8.0.21
    container_name: wetalk-db
    ports:
      - 3336:3306
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - wetalk-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    depends_on:
      - wetalk-db
    environment:
      - PMA_HOST=wetalk-db # Note the "mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - wetalk-network

# BE
  wetalk-feed:
    build:
      context: ./
      dockerfile: backend/feed/Dockerfile
    depends_on:
      - wetalk-db
    environment:
      - PORT=3001
      - APP_NAME=feed
    ports:
      - 8081:8080
    restart: on-failure
    volumes:
      - feed_volume:/usr/src/feed/
    networks:
      - wetalk-network

  wetalk-comment:
    build:
      context: ./
      dockerfile: ./backend/comment/Dockerfile
    depends_on:
      - wetalk-db
    environment:
      - PORT=3001
      - APP_NAME=comment
    ports:
      - 8082:8080
    restart: on-failure
    volumes:
      - comment_volume:/usr/src/comment/
    networks:
      - wetalk-network

#  FE
  wetalk-frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 8083:3000
    restart: on-failure
    networks:
      - wetalk-network

volumes:
  feed_volume:
  comment_volume:
  db_volume:

networks:
  wetalk-network:
    driver: bridge
