// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: feed/feed.proto

package feed

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Privacy int32

const (
	Privacy_UNSPECIFIED Privacy = 0
	Privacy_PRIVATE     Privacy = 1
	Privacy_PUBLIC      Privacy = 2
)

// Enum value maps for Privacy.
var (
	Privacy_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "PRIVATE",
		2: "PUBLIC",
	}
	Privacy_value = map[string]int32{
		"UNSPECIFIED": 0,
		"PRIVATE":     1,
		"PUBLIC":      2,
	}
)

func (x Privacy) Enum() *Privacy {
	p := new(Privacy)
	*p = x
	return p
}

func (x Privacy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Privacy) Descriptor() protoreflect.EnumDescriptor {
	return file_feed_feed_proto_enumTypes[0].Descriptor()
}

func (Privacy) Type() protoreflect.EnumType {
	return &file_feed_feed_proto_enumTypes[0]
}

func (x Privacy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Privacy.Descriptor instead.
func (Privacy) EnumDescriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{0}
}

type PostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AudioUrl   string  `protobuf:"bytes,1,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	Caption    string  `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	Transcript string  `protobuf:"bytes,3,opt,name=transcript,proto3" json:"transcript,omitempty"`
	Privacy    Privacy `protobuf:"varint,4,opt,name=privacy,proto3,enum=feed.Privacy" json:"privacy,omitempty"`
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_feed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{0}
}

func (x *PostRequest) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

func (x *PostRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *PostRequest) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *PostRequest) GetPrivacy() Privacy {
	if x != nil {
		return x.Privacy
	}
	return Privacy_UNSPECIFIED
}

type PostReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeedId string `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
}

func (x *PostReply) Reset() {
	*x = PostReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feed_feed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReply) ProtoMessage() {}

func (x *PostReply) ProtoReflect() protoreflect.Message {
	mi := &file_feed_feed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReply.ProtoReflect.Descriptor instead.
func (*PostReply) Descriptor() ([]byte, []int) {
	return file_feed_feed_proto_rawDescGZIP(), []int{1}
}

func (x *PostReply) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

var File_feed_feed_proto protoreflect.FileDescriptor

var file_feed_feed_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x65, 0x65, 0x64, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x66, 0x65, 0x65, 0x64, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xa3, 0x01, 0x0a, 0x0b, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x25, 0x0a, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72, 0x03, 0x88, 0x01, 0x01, 0x52, 0x08, 0x61,
	0x75, 0x64, 0x69, 0x6f, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x12, 0x33, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x63,
	0x79, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x82, 0x01, 0x04, 0x10, 0x01, 0x20, 0x00, 0x52, 0x07, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x22, 0x24, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x65, 0x65, 0x64, 0x49, 0x64, 0x2a, 0x33, 0x0a, 0x07,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x63, 0x79, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x49, 0x56,
	0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x10,
	0x02, 0x32, 0x34, 0x0a, 0x04, 0x46, 0x65, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x04, 0x50, 0x6f, 0x73,
	0x74, 0x12, 0x11, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x63, 0x73, 0x65, 0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x72,
	0x65, 0x70, 0x6f, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x66, 0x65, 0x65, 0x64, 0x3b, 0x66, 0x65, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_feed_feed_proto_rawDescOnce sync.Once
	file_feed_feed_proto_rawDescData = file_feed_feed_proto_rawDesc
)

func file_feed_feed_proto_rawDescGZIP() []byte {
	file_feed_feed_proto_rawDescOnce.Do(func() {
		file_feed_feed_proto_rawDescData = protoimpl.X.CompressGZIP(file_feed_feed_proto_rawDescData)
	})
	return file_feed_feed_proto_rawDescData
}

var file_feed_feed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_feed_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_feed_feed_proto_goTypes = []interface{}{
	(Privacy)(0),        // 0: feed.Privacy
	(*PostRequest)(nil), // 1: feed.PostRequest
	(*PostReply)(nil),   // 2: feed.PostReply
}
var file_feed_feed_proto_depIdxs = []int32{
	0, // 0: feed.PostRequest.privacy:type_name -> feed.Privacy
	1, // 1: feed.Feed.Post:input_type -> feed.PostRequest
	2, // 2: feed.Feed.Post:output_type -> feed.PostReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_feed_feed_proto_init() }
func file_feed_feed_proto_init() {
	if File_feed_feed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_feed_feed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_feed_feed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feed_feed_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feed_feed_proto_goTypes,
		DependencyIndexes: file_feed_feed_proto_depIdxs,
		EnumInfos:         file_feed_feed_proto_enumTypes,
		MessageInfos:      file_feed_feed_proto_msgTypes,
	}.Build()
	File_feed_feed_proto = out.File
	file_feed_feed_proto_rawDesc = nil
	file_feed_feed_proto_goTypes = nil
	file_feed_feed_proto_depIdxs = nil
}
