// Code generated by entc, DO NOT EDIT.

package feed

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the feed type in the database.
	Label = "feed"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFeedID holds the string denoting the feed_id field in the database.
	FieldFeedID = "feed_id"
	// FieldAudioURL holds the string denoting the audio_url field in the database.
	FieldAudioURL = "audio_url"
	// FieldCaption holds the string denoting the caption field in the database.
	FieldCaption = "caption"
	// FieldTranscript holds the string denoting the transcript field in the database.
	FieldTranscript = "transcript"
	// FieldPrivacy holds the string denoting the privacy field in the database.
	FieldPrivacy = "privacy"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"

	// Table holds the table name of the feed in the database.
	Table = "feeds"
)

// Columns holds all SQL columns for feed fields.
var Columns = []string{
	FieldID,
	FieldFeedID,
	FieldAudioURL,
	FieldCaption,
	FieldTranscript,
	FieldPrivacy,
	FieldOwnerID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

var (
	// DefaultFeedID holds the default value on creation for the feed_id field.
	DefaultFeedID func() uuid.UUID
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updated_at field.
	DefaultUpdatedAt func() time.Time
)

// Privacy defines the type for the privacy enum field.
type Privacy string

// PrivacyPUBLIC is the default Privacy.
const DefaultPrivacy = PrivacyPUBLIC

// Privacy values.
const (
	PrivacyPRIVATE Privacy = "PRIVATE"
	PrivacyPUBLIC  Privacy = "PUBLIC"
)

func (pr Privacy) String() string {
	return string(pr)
}

// PrivacyValidator is a validator for the "privacy" field enum values. It is called by the builders before save.
func PrivacyValidator(pr Privacy) error {
	switch pr {
	case PrivacyPRIVATE, PrivacyPUBLIC:
		return nil
	default:
		return fmt.Errorf("feed: invalid enum value for privacy field: %q", pr)
	}
}
