listener:
  tcp:
    address: 0.0.0.0
    port: 8080
    secure: false

logger:
  pretty: true
  level: DEBUG

database:
#  url: root:yG!C7d8WCk@tcp(db-feed:3306)/wetalk-feed?charset=utf8&parseTime=true
  url: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}?charset=utf8&parseTime=true
  debug: false
