// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: comment/comment.proto

package comment

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _comment_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on CommentRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CommentRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for FeedId

	// no validation rules for Content

	return nil
}

// CommentRequestValidationError is the validation error returned by
// CommentRequest.Validate if the designated constraints aren't met.
type CommentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentRequestValidationError) ErrorName() string { return "CommentRequestValidationError" }

// Error satisfies the builtin error interface
func (e CommentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentRequestValidationError{}

// Validate checks the field values on CommentReply with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *CommentReply) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for CommentId

	return nil
}

// CommentReplyValidationError is the validation error returned by
// CommentReply.Validate if the designated constraints aren't met.
type CommentReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommentReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommentReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommentReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommentReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommentReplyValidationError) ErrorName() string { return "CommentReplyValidationError" }

// Error satisfies the builtin error interface
func (e CommentReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommentReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommentReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommentReplyValidationError{}
